const ActionType = {
    LOAD_SCHEMA: 'LOAD_SCHEMA'
    , SCHEMA_LOADED: 'SCHEMA_LOADED'
    , CREATE_SCHEMA: 'CREATE_SCHEMA'
    , UPDATE_SCHEMA_ROWS: 'UPDATE_SCHEMA_ROWS'
    , DELETE_SCHEMA_ROW: 'DELETE_SCHEMA_ROW'
    , ADD_SCHEMA_ROW: 'ADD_SCHEMA_ROW'
};

export default ActionType;